name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'readme.md'
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      should_run: ${{ steps.set-matrix.outputs.should_run }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Detect changed components
        id: changes
        uses: dorny/paths-filter@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            oauth:
              - 'oauth/**'
            worker:
              - 'worker/**'

      - name: Build dynamic matrix
        id: set-matrix
        shell: bash
        run: |
          components=()
          if [[ "${{ steps.changes.outputs.oauth }}" == 'true' ]]; then components+=('"oauth"'); fi
          if [[ "${{ steps.changes.outputs.worker }}" == 'true' ]]; then components+=('"worker"'); fi

          if [ ${#components[@]} -eq 0 ]; then
            echo 'matrix={"extra":[]}' >> "$GITHUB_OUTPUT"
            echo 'should_run=false' >> "$GITHUB_OUTPUT"
            echo "No component changes detected — skipping build."
          else
            echo "matrix={\"extra\":[${components[*]}]}" >> "$GITHUB_OUTPUT"
            echo 'should_run=true' >> "$GITHUB_OUTPUT"
            echo "Will build components: [${components[*]}]"
          fi

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.changes.outputs.matrix) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Container image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ghcr.io/${{ github.repository }}
          tags: ${{ matrix.extra }}
          containerfiles: ./dockerfile
          build-args: EXTRA=${{ matrix.extra }}

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ghcr.io/${{ github.repository }}
          tags: ${{ matrix.extra }}
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
